/* ¡ */
#define ES_INVERTED_EXCLAMATION (ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_EQUAL_AND_PLUS))
#define ES_IEXCL (ES_INVERTED_EXCLAMATION)

/* ¿ */
#define ES_INVERTED_QUESTION (LS(ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_EQUAL_AND_PLUS)))
#define ES_IQMARK (ES_INVERTED_QUESTION)

/* ñ */
#define ES_N_TILDE (ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_SEMICOLON_AND_COLON))
